export const FETCH_USER = 'fetch_user'
export const CHAT_USER = 'chat_user'


export const ALL_PRODUCTS = 'all_products'



export const DUMMY = 'dummy'

export const SINGLE_PRODUCT_INFO = 'SINGLE_PRODUCT_INFO'
export const SINGLE_PRODUCT_RAW_MATERIALS = 'SINGLE_PRODUCT_RAW_MATERIALS'
export const SINGLE_PRODUCT_APPLICATION = 'SINGLE_PRODUCT_APPLICATION'
export const SINGLE_PRODUCT_SUPPLIER = 'SINGLE_PRODUCT_SUPPLIER'
export const SINGLE_PRODUCT_ACTIVITY = 'SINGLE_PRODUCT_ACTIVITY'
export const FOLLOWED_PRODUCTS = 'FOLLOWED_PRODUCTS'


export const RECOMMENDED_PRODUCTS = 'RECOMMENDED_PRODUCTS'
export const POTENTIAL_CUSTOMERS = 'POTENTIAL_CUSTOMERS'

export const SINGLE_COMPANY_INFO = 'SINGLE_COMPANY_INFO'

export const NETWORK_USER_FEED = "NETWORK_USER_FEED";
export const POST_STATUS = "POST_STATUS";
export const NETWORK_PRODUCT_FEED = "NETWORK_PRODUCT_FEED";
export const GLOBAL_USER_FEED = "GLOBAL_USER_FEED";
export const UPDATE_USERINFO_COLLECTION = "UPDATE_USERINFO_COLLECTION";
export const USERINFO = "USERINFO";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const NETWORK_USER_LIKED_POSTS = "NETWORK_USER_LIKED_POSTS";
export const SET_POST_COMMENTS = "SET_POST_COMMENTS";
export const POST_LIKES_COUNT = "POST_LIKES_COUNT";
export const ADD_POST_COMMENT_STATUS = "ADD_POST_COMMENT_STATUS"; 
